### ISSUE TITLE
Possible bug in `+` operator overload for `Gt`

### ISSUE THREAD

**Issue by AnnaShaleva** [neo-project/Neo.Cryptography.BLS12_381#4]
Could you, please, check that there's no error in `+` operator overload for `Gt` struct? I think that there should be `+` sign instead of `*`:
https://github.com/neo-project/Neo.Cryptography.BLS12_381/blob/844bc3a4f7d8ba2c545ace90ca124f8ada4c8d29/src/Neo.Cryptography.BLS12_381/Gt.cs#L94

**Comment by Jim8y** [comment]
It is `*`, please refer https://github.com/zkcrypto/bls12_381/blob/7de7b9d9c509b9973b35a3241b74bbbea95e700a/src/pairings.rs#L283

**Comment by AnnaShaleva** [comment]
My bad, thank you!
